/* tslint:disable */
/* eslint-disable */
/**
 * IncidentLog API
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IncidentType,
} from '../models';
import {
    IncidentTypeFromJSON,
    IncidentTypeToJSON,
} from '../models';

/**
 * IncidentTypesApi - interface
 * 
 * @export
 * @interface IncidentTypesApiInterface
 */
export interface IncidentTypesApiInterface {
    /**
     * Returns list of predefined hospital incident types.
     * @summary Provides the list of predefined incident types
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IncidentTypesApiInterface
     */
    getIncidentTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IncidentType>>>;

    /**
     * Returns list of predefined hospital incident types.
     * Provides the list of predefined incident types
     */
    getIncidentTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IncidentType>>;

}

/**
 * 
 */
export class IncidentTypesApi extends runtime.BaseAPI implements IncidentTypesApiInterface {

    /**
     * Returns list of predefined hospital incident types.
     * Provides the list of predefined incident types
     */
    async getIncidentTypesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IncidentType>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/incident-types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IncidentTypeFromJSON));
    }

    /**
     * Returns list of predefined hospital incident types.
     * Provides the list of predefined incident types
     */
    async getIncidentTypes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IncidentType>> {
        const response = await this.getIncidentTypesRaw(initOverrides);
        return await response.value();
    }

}
