/* tslint:disable */
/* eslint-disable */
/**
 * IncidentLog API
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Incident,
} from '../models';
import {
    IncidentFromJSON,
    IncidentToJSON,
} from '../models';

/**
 * IncidentLogApi - interface
 * 
 * @export
 * @interface IncidentLogApiInterface
 */
export interface IncidentLogApiInterface {
    /**
     * Returns current and historical incident reports
     * @summary Provides the list of incidents
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IncidentLogApiInterface
     */
    getIncidentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Incident>>>;

    /**
     * Returns current and historical incident reports
     * Provides the list of incidents
     */
    getIncidents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Incident>>;

}

/**
 * 
 */
export class IncidentLogApi extends runtime.BaseAPI implements IncidentLogApiInterface {

    /**
     * Returns current and historical incident reports
     * Provides the list of incidents
     */
    async getIncidentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Incident>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/incidents`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IncidentFromJSON));
    }

    /**
     * Returns current and historical incident reports
     * Provides the list of incidents
     */
    async getIncidents(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Incident>> {
        const response = await this.getIncidentsRaw(initOverrides);
        return await response.value();
    }

}
