/* tslint:disable */
/* eslint-disable */
/**
 * IncidentLog API
 * Incident reporting and security event management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IncidentSeverity } from './IncidentSeverity';
import {
    IncidentSeverityFromJSON,
    IncidentSeverityFromJSONTyped,
    IncidentSeverityToJSON,
} from './IncidentSeverity';
import type { IncidentStatus } from './IncidentStatus';
import {
    IncidentStatusFromJSON,
    IncidentStatusFromJSONTyped,
    IncidentStatusToJSON,
} from './IncidentStatus';

/**
 * 
 * @export
 * @interface Incident
 */
export interface Incident {
    /**
     * Unique id of the incident
     * @type {string}
     * @memberof Incident
     */
    id: string;
    /**
     * Type of the incident
     * @type {string}
     * @memberof Incident
     */
    incidentType: string;
    /**
     * Place where the incident occurred
     * @type {string}
     * @memberof Incident
     */
    location: string;
    /**
     * Date and time when the incident occurred
     * @type {Date}
     * @memberof Incident
     */
    occurredAt: Date;
    /**
     * Description of the incident
     * @type {string}
     * @memberof Incident
     */
    description: string;
    /**
     * 
     * @type {IncidentSeverity}
     * @memberof Incident
     */
    severity: IncidentSeverity;
    /**
     * 
     * @type {IncidentStatus}
     * @memberof Incident
     */
    status: IncidentStatus;
    /**
     * List of attached files
     * @type {Array<string>}
     * @memberof Incident
     */
    attachments?: Array<string>;
    /**
     * Investigation report
     * @type {string}
     * @memberof Incident
     */
    investigationReport?: string;
    /**
     * Additional notes
     * @type {string}
     * @memberof Incident
     */
    notes?: string;
}

/**
 * Check if a given object implements the Incident interface.
 */
export function instanceOfIncident(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "incidentType" in value;
    isInstance = isInstance && "location" in value;
    isInstance = isInstance && "occurredAt" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "severity" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function IncidentFromJSON(json: any): Incident {
    return IncidentFromJSONTyped(json, false);
}

export function IncidentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Incident {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'incidentType': json['incidentType'],
        'location': json['location'],
        'occurredAt': (new Date(json['occurredAt'])),
        'description': json['description'],
        'severity': IncidentSeverityFromJSON(json['severity']),
        'status': IncidentStatusFromJSON(json['status']),
        'attachments': !exists(json, 'attachments') ? undefined : json['attachments'],
        'investigationReport': !exists(json, 'investigationReport') ? undefined : json['investigationReport'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function IncidentToJSON(value?: Incident | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'incidentType': value.incidentType,
        'location': value.location,
        'occurredAt': (value.occurredAt.toISOString()),
        'description': value.description,
        'severity': IncidentSeverityToJSON(value.severity),
        'status': IncidentStatusToJSON(value.status),
        'attachments': value.attachments,
        'investigationReport': value.investigationReport,
        'notes': value.notes,
    };
}

