/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IncidentApp {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
    }
    interface IncidentEditor {
        /**
          * @default '/api'
         */
        "apiBase": string;
        "entryId": string;
    }
    interface IncidentList {
        /**
          * @default '/api'
         */
        "apiBase": string;
    }
}
export interface IncidentEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIncidentEditorElement;
}
export interface IncidentListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIncidentListElement;
}
declare global {
    interface HTMLIncidentAppElement extends Components.IncidentApp, HTMLStencilElement {
    }
    var HTMLIncidentAppElement: {
        prototype: HTMLIncidentAppElement;
        new (): HTMLIncidentAppElement;
    };
    interface HTMLIncidentEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLIncidentEditorElement extends Components.IncidentEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIncidentEditorElementEventMap>(type: K, listener: (this: HTMLIncidentEditorElement, ev: IncidentEditorCustomEvent<HTMLIncidentEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIncidentEditorElementEventMap>(type: K, listener: (this: HTMLIncidentEditorElement, ev: IncidentEditorCustomEvent<HTMLIncidentEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIncidentEditorElement: {
        prototype: HTMLIncidentEditorElement;
        new (): HTMLIncidentEditorElement;
    };
    interface HTMLIncidentListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLIncidentListElement extends Components.IncidentList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIncidentListElementEventMap>(type: K, listener: (this: HTMLIncidentListElement, ev: IncidentListCustomEvent<HTMLIncidentListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIncidentListElementEventMap>(type: K, listener: (this: HTMLIncidentListElement, ev: IncidentListCustomEvent<HTMLIncidentListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIncidentListElement: {
        prototype: HTMLIncidentListElement;
        new (): HTMLIncidentListElement;
    };
    interface HTMLElementTagNameMap {
        "incident-app": HTMLIncidentAppElement;
        "incident-editor": HTMLIncidentEditorElement;
        "incident-list": HTMLIncidentListElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface IncidentApp {
        "apiBase"?: string;
        /**
          * @default ''
         */
        "basePath"?: string;
    }
    interface IncidentEditor {
        /**
          * @default '/api'
         */
        "apiBase"?: string;
        "entryId": string;
        "onEditor-closed"?: (event: IncidentEditorCustomEvent<string>) => void;
    }
    interface IncidentList {
        /**
          * @default '/api'
         */
        "apiBase"?: string;
        "onEntry-clicked"?: (event: IncidentListCustomEvent<string>) => void;
    }

    interface IncidentAppAttributes {
        "basePath": string;
        "apiBase": string;
    }
    interface IncidentEditorAttributes {
        "entryId": string;
        "apiBase": string;
    }
    interface IncidentListAttributes {
        "apiBase": string;
    }

    interface IntrinsicElements {
        "incident-app": Omit<IncidentApp, keyof IncidentAppAttributes> & { [K in keyof IncidentApp & keyof IncidentAppAttributes]?: IncidentApp[K] } & { [K in keyof IncidentApp & keyof IncidentAppAttributes as `attr:${K}`]?: IncidentAppAttributes[K] } & { [K in keyof IncidentApp & keyof IncidentAppAttributes as `prop:${K}`]?: IncidentApp[K] };
        "incident-editor": Omit<IncidentEditor, keyof IncidentEditorAttributes> & { [K in keyof IncidentEditor & keyof IncidentEditorAttributes]?: IncidentEditor[K] } & { [K in keyof IncidentEditor & keyof IncidentEditorAttributes as `attr:${K}`]?: IncidentEditorAttributes[K] } & { [K in keyof IncidentEditor & keyof IncidentEditorAttributes as `prop:${K}`]?: IncidentEditor[K] } & OneOf<"entryId", IncidentEditor["entryId"], IncidentEditorAttributes["entryId"]>;
        "incident-list": Omit<IncidentList, keyof IncidentListAttributes> & { [K in keyof IncidentList & keyof IncidentListAttributes]?: IncidentList[K] } & { [K in keyof IncidentList & keyof IncidentListAttributes as `attr:${K}`]?: IncidentListAttributes[K] } & { [K in keyof IncidentList & keyof IncidentListAttributes as `prop:${K}`]?: IncidentList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "incident-app": LocalJSX.IntrinsicElements["incident-app"] & JSXBase.HTMLAttributes<HTMLIncidentAppElement>;
            "incident-editor": LocalJSX.IntrinsicElements["incident-editor"] & JSXBase.HTMLAttributes<HTMLIncidentEditorElement>;
            "incident-list": LocalJSX.IntrinsicElements["incident-list"] & JSXBase.HTMLAttributes<HTMLIncidentListElement>;
        }
    }
}
