/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IncidentList {
    }
}
declare global {
    interface HTMLIncidentListElement extends Components.IncidentList, HTMLStencilElement {
    }
    var HTMLIncidentListElement: {
        prototype: HTMLIncidentListElement;
        new (): HTMLIncidentListElement;
    };
    interface HTMLElementTagNameMap {
        "incident-list": HTMLIncidentListElement;
    }
}
declare namespace LocalJSX {
    interface IncidentList {
    }
    interface IntrinsicElements {
        "incident-list": IncidentList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "incident-list": LocalJSX.IntrinsicElements["incident-list"] & JSXBase.HTMLAttributes<HTMLIncidentListElement>;
        }
    }
}
